In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\S LAXMI VYSHNAVI\Documents\ecommerce_data.csv", 
                 encoding='latin1')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\S LAXMI VYSHNAVI\\Documents\\ecommerce_data.csv'

In [2]:
import pandas as pd
import os

# Find the file
for root, dirs, files in os.walk(r"C:\Users\S LAXMI VYSHNAVI"):
    for file in files:
        if 'ecommerce' in file.lower():
            print(os.path.join(root, file))

C:\Users\S LAXMI VYSHNAVI\AppData\Roaming\Microsoft\Office\Recent\ecommerce_data.LNK
C:\Users\S LAXMI VYSHNAVI\AppData\Roaming\Microsoft\Windows\Network Shortcuts\ecommerce_data.csv
C:\Users\S LAXMI VYSHNAVI\AppData\Roaming\Microsoft\Windows\Recent\ecommerce_data.lnk

In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\S LAXMI VYSHNAVI\Downloads\ecommerce_data.csv", 
                 encoding='latin1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom

In [4]:
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData Types:")
print(df.dtypes)

Shape: (541909, 8)

Columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

Data Types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [5]:
print("Missing Values:")
print(df.isnull().sum())
print("\nMissing Percentage:")
print(round(df.isnull().sum() / len(df) * 100, 2))

Missing Values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing Percentage:
InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

print("\nBasic Statistics:")
df.describe()

Duplicate rows: 5268

Basic Statistics:

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [7]:
df_clean = df.drop_duplicates()
print("Rows after removing duplicates:", len(df_clean))


df_clean = df_clean.dropna(subset=['CustomerID'])
print("Rows after removing missing CustomerID:", len(df_clean))


df_clean = df_clean[df_clean['Quantity'] > 0]
df_clean = df_clean[df_clean['UnitPrice'] > 0]
print("Rows after removing negatives:", len(df_clean))

print("\nFinal clean dataset shape:", df_clean.shape)

Rows after removing duplicates: 536641
Rows after removing missing CustomerID: 401604
Rows after removing negatives: 392692

Final clean dataset shape: (392692, 8)

In [8]:
df_clean = df_clean.copy()
df_clean['TotalPrice'] = df_clean['Quantity'] * df_clean['UnitPrice']


df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])


df_clean['Year'] = df_clean['InvoiceDate'].dt.year
df_clean['Month'] = df_clean['InvoiceDate'].dt.month

print("New columns added!")
print(df_clean.head())

ValueError: time data "12/13/2010 9:02" doesn't match format "%m-%d-%Y %H:%M", at position 813. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [9]:
df_clean = df_clean.copy()


df_clean['TotalPrice'] = df_clean['Quantity'] * df_clean['UnitPrice']


df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'], 
                                          format='mixed')


df_clean['Year'] = df_clean['InvoiceDate'].dt.year
df_clean['Month'] = df_clean['InvoiceDate'].dt.month

print("New columns added!")
print(df_clean.head())

New columns added!
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34

   Year  Month
0  2010     12
1  2010     12
2  2010     12
3  2010     12
4  2010     12

In [10]:
print("Dataset Shape:", df_clean.shape)

print("\nMissing Values:")
print(df_clean.isnull().sum())

print("\nDuplicate Rows:")
print(df_clean.duplicated().sum())

Dataset Shape: (392692, 11)

Missing Values:
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
Year           0
Month          0
dtype: int64

Duplicate Rows:
0

In [11]:
df_clean.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,TotalPrice,Year,Month
count,392692.000000,392692,392692.000000,392692.000000,392692.000000,392692.000000,392692.000000
mean,13.119702,2011-07-10 19:13:07.771892480,3.125914,15287.843865,22.631500,2010.934631,7.601871
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000,2010.000000,1.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13955.000000,4.950000,2011.000000,5.000000
50%,6.000000,2011-07-31 12:02:00,1.950000,15150.000000,12.450000,2011.000000,8.000000
75%,12.000000,2011-10-20 12:53:00,3.750000,16791.000000,19.800000,2011.000000,11.000000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000,2011.000000,12.000000
std,180.492832,NaN,22.241836,1713.539549,311.099224,0.247177,3.415015

In [12]:
df_clean.to_csv("cleaned_ecommerce_data.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!